museum_of_dreams_project/urls.py
"""
URL configuration for museum_of_dreams_project project.
"""

from django.conf import settings
from django.conf.urls import include, handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.contrib.auth.views import LogoutView
from django.views.generic.base import RedirectView

from django_distill import distill_path

from mod_app import views

if settings.ENVIRONMENT == "production":
    admin.site.site_header = "Administration for Museum of Dreamworlds Site"
    admin.site.site_title = "Museum of Dreamworlds Admin Site"
    admin.site.index_title = "Admin"
else:
    admin.site.site_header = "Administration for Museum of Dreams (staging)"
    admin.site.site_title = "Museum of Dreams Staging Admin Site"
    admin.site.index_title = "Admin (staging)"

urlpatterns = (
    [
        path("grappelli/", include("grappelli.urls")),
        path("grappelli-docs/", include("grappelli.urls_docs")),
        path("ckeditor/", include("ckeditor_uploader.urls")),
        path("admin/", admin.site.urls, name=admin),
        path("logout", LogoutView.as_view(next_page="/"), name="logout"),
        path(
            "view_bucket_items/",
            views.BucketItemsView.as_view(),
            name="view_bucket_items",
        ),
        distill_path(
            "", views.HomeView.as_view(), name="home", distill_file="index.html"
        ),
        path(
            "favicon.ico",
            RedirectView.as_view(url=f"{settings.STATIC_URL}admin/img/favicon.ico"),
        ),
        path("mentions-api", views.MentionsApiView.as_view(), name="mentions_api"),
        # website pages
        distill_path(
            "films",
            views.FilmListView.as_view(),
            name="film_list",
        ),
        distill_path(
            "films/<pk>",
            views.FilmDetailView.as_view(),
            name="film_detail",
        ),
        distill_path(
            "analyses",
            views.AnalysisListView.as_view(),
            name="analysis_list",
        ),
        distill_path(
            "analyses/<pk>",
            views.AnalysisDetailView.as_view(),
            name="analysis_detail",
        ),
        distill_path(
            "teaching-resources",
            views.TRListView.as_view(),
            name="tr_list",
        ),
        distill_path(
            "teaching-resources/<pk>",
            views.TRDetailView.as_view(),
            name="tr_detail",
        ),
        distill_path(
            "bibliography",
            views.BibliographyListView.as_view(),
            name="bibliography",
        ),
        distill_path(
            "search",
            views.custom_404,
            name="search",
        ),
        distill_path(
            "locations",
            views.custom_404,
            name="location_list",
        ),
        distill_path(
            "tags",
            views.TagListView.as_view(),
            name="tag_list",
        ),
        distill_path(
            "tags/<pk>",
            views.TagDetailView.as_view(),
            name="tag_detail",
        ),
        path(
            "download-analysis/<pk>", views.downloadAnalysis, name="download_analysis"
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

handler404 = "mod_app.views.custom_404"

mod_app/models/bibliography_model.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.html import strip_tags


class BibliographyItem(models.Model):
    """These should be automatically added to relevant bibliographies by the extract_citations.py file"""

    class Meta:
        ordering = ["short_citation"]

    def __str__(self):
        plain_text = strip_tags(self.full_citation).replace("&nbsp;", " ")
        return f"\n{plain_text}"

    short_citation = models.CharField(
        max_length=200,
        null=True,
        help_text="Please use Harvard in-text citation style. Examples: (Author surname, year), or in the case of up to 3 authors: (Author 1 surname, Author 2 surname, Author 3 surname, year), or in the case or more than 3 authors: (Author 1 surname, et al., year) ",
    )
    full_citation = RichTextField(
        null=True,
        help_text="Please use Harvard reference list style. Examples: Author surname, initial. (year). 'Title of article/book/website/photograph'. Available at: URL or DOI where applicable (date accessed). Please note that the website or photo title should be italicised. For more detailed information and examples visit: https://www5.open.ac.uk/library/referencing-and-plagiarism/quick-guide-to-harvard-referencing-cite-them-right",
    )
    annotation = RichTextField(
        null=True,
        blank=True,
        help_text="Notes on how this item was helpful or relevant, for example.",
    )

mod_app/models/project_note_model.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

from .bibliography_model import BibliographyItem
from ..utils.extract_citations import update_bibliography


class ProjectNote(models.Model):
    class Meta:
        verbose_name = "Research Framework"

    def __str__(self):
        return self.title

    title = models.CharField(max_length=255, null=False)

    content = RichTextUploadingField(
        null=True,
        blank=True,
        help_text="Mentions are available here.",
    )

    bibliography = models.ManyToManyField(
        BibliographyItem,
        blank=True,
        related_name="project_notes",
        help_text="This field updates on save, and some items may not be visible immediately",
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        update_bibliography(self, [self.content])

mod_app/models/teaching_analysis_models.py
from bs4 import BeautifulSoup
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

from ..utils.extract_citations import update_bibliography

from mod_app.models import Tag, Keyword, Topic, BibliographyItem


def display_list(list):
    if len(list) > 1:
        display_list = ", ".join(str(f) for f in list[:-1]) + f", and {list[-1]}"
    else:
        display_list = str(list[0])
    return display_list


def strip_empty_paragraphs(content):
    """There seems to be some weird behaviour wherein CKEditor is adding empty paragraphs after videos. We don't want this on the front end nor in the actual content field, so this function removes any <p>&nbsp;</p> that immediately follow a video div."""
    soup = BeautifulSoup(content, "html.parser")

    video_divs = soup.find_all("div", class_="ckeditor-html5-video")

    for div in video_divs:
        next_element = div.next_sibling

        # Keep checking and removing consecutive <p>&nbsp;</p> elements
        while True:
            # Skip whitespace text nodes
            while (
                next_element
                and isinstance(next_element, str)
                and next_element.strip() == ""
            ):
                next_element = next_element.next_sibling

            # Check if next element is <p>&nbsp;</p> or <p></p>
            if (
                next_element
                and next_element.name == "p"
                and (
                    next_element.encode_contents() == b"&nbsp;"
                    or next_element.get_text() == "\xa0"
                    or next_element.string == "\xa0"
                    or not next_element.contents
                )
            ):
                # Store the next sibling before removing the current element
                next_to_check = next_element.next_sibling
                # Remove the <p>&nbsp;</p> element and move to the next
                next_element.decompose()
                next_element = next_to_check
            else:
                # Break loop when we get back to real content
                break

    cleaned_html = str(soup)
    return cleaned_html


class Analysis(models.Model):
    class Meta:
        verbose_name_plural = "Analyses"

    def __str__(self):
        return self.title

    def default_title():
        return f"Analysis {Analysis.objects.count() + 1}"

    title = models.CharField(max_length=255, default=default_title)

    summary = models.TextField(max_length=1500, null=True, blank=True)

    content = RichTextUploadingField(
        null=True,
        blank=True,
        help_text="Mentions are available here and will contibute to the bibliography.",
    )

    films = models.ManyToManyField("Film", related_name="analyses", blank=True)

    topics = models.ManyToManyField(Topic, related_name="analysis_topics", blank=True)

    keywords = models.ManyToManyField(
        Keyword, related_name="analysis_keywords", blank=True
    )

    genre = models.ManyToManyField(Tag, related_name="analysis_genres", blank=True)

    holdings = models.CharField(max_length=400, blank=True, null=True)

    work_history = models.TextField(blank=True)

    teaching_resources = models.ManyToManyField(
        "TeachingResources", related_name="analyses", blank=True
    )

    bibliography = models.ManyToManyField(
        BibliographyItem,
        related_name="analyses",
        help_text="This field updates on save, and some items may not be visible immediately",
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.content is not None and len(self.content) > 0:
            self.content = strip_empty_paragraphs(self.content)

        update_bibliography(self, [self.content])


class TeachingResources(models.Model):
    class Meta:
        verbose_name_plural = "Teaching Resources"

    def __str__(self):
        return self.title

    def default_title():
        return f"Teaching Resources bundle{TeachingResources.objects.count() + 1}"

    title = models.CharField(max_length=255, default=default_title)
    material = RichTextUploadingField(
        null=True,
        blank=True,
        help_text="Mentions are available here and will contibute to the bibliography.",
    )

    films = models.ManyToManyField("Film", related_name="trs", blank=True)

    topics = models.ManyToManyField(Topic, related_name="tr_topics", blank=True)

    keywords = models.ManyToManyField(Keyword, related_name="tr_keywords", blank=True)

    tags = models.ManyToManyField(Tag, related_name="tr_tags", blank=True)

    bibliography = models.ManyToManyField(
        BibliographyItem,
        related_name="teaching_resources",
        help_text="This field updates on save, and some items may not be visible immediately",
    )

    clips = models.ManyToManyField(
        "Video",
        related_name="tr_clips",
        blank=True,
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        update_bibliography(self, [self.material])

mod_app/views.py
import re
from urllib.parse import quote

import boto3
from bs4 import BeautifulSoup
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.template.defaultfilters import striptags
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from xhtml2pdf import pisa

# you may need to comment out the bwlow import when running locally if you get a socket error
from museum_of_dreams_project.settings.aws import (
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_STORAGE_BUCKET_NAME,
)

from .models import Analysis, BibliographyItem, Film, Tag, TeachingResources


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        films_with_images = Film.objects.filter(cardimages__isnull=False)
        random_films = films_with_images.order_by("?")[:5]

        slides = []
        if random_films:
            for film in random_films:
                if film.cardimages.first().url:
                    slides.append(film.cardimages.first().url)
                else:
                    slides.append(film.cardimages.first().file.url)

        context["slides"] = slides
        context["slide_images"] = True
        return context


class FilmListView(ListView):
    model = Film
    template_name = "film_list.html"
    paginate_by = 20

    def get_paginate_by(self, queryset):
        page = self.request.GET.get(self.page_kwarg)
        if page:
            return self.paginate_by
        else:
            return None


class FilmDetailView(DetailView):
    model = Film
    template_name = "film_detail.html"
    context_object_name = "film"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        film = self.object

        printed_material_slides = (
            list(film.scripts.all())
            + list(film.pressbooks.all())
            + list(film.programmes.all())
            + list(film.publicitys.all())
        )

        visual_resources_slides = (
            list(film.stills.all())
            + list(film.drawings.all())
            + list(film.posters.all())
            + list(film.postcards.all())
        )

        context["pm_slides"] = printed_material_slides
        context["vr_slides"] = visual_resources_slides

        context["video_slides"] = film.videos.all()
        return context


class MentionsApiView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get("query", "")
        # search by full citation but return short one
        queryset = BibliographyItem.objects.filter(full_citation__icontains=query)
        mentions_data = [
            {
                "id": item.id,
                "short_citation": item.short_citation,
                "full_citation": striptags(item.full_citation)
                .replace("&nbsp;", " ")
                .replace("&amp;", "&"),  # making plain text
            }
            for item in queryset
        ]
        return JsonResponse(mentions_data, safe=False)


class AnalysisListView(ListView):
    model = Analysis
    template_name = "analysis_list.html"
    paginate_by = 20

    def get_paginate_by(self, queryset):
        page = self.request.GET.get(self.page_kwarg)
        if page:
            return self.paginate_by
        else:
            return None


class AnalysisDetailView(DetailView):
    model = Analysis
    template_name = "analysis_detail.html"
    context_object_name = "analysis"


class TRListView(ListView):
    model = TeachingResources
    template_name = "tr_list.html"
    paginate_by = 20

    def get_paginate_by(self, queryset):
        page = self.request.GET.get(self.page_kwarg)
        if page:
            return self.paginate_by
        else:
            return None


class TRDetailView(DetailView):
    model = TeachingResources
    template_name = "tr_detail.html"
    context_object_name = "tr"


class TagListView(ListView):
    model = Tag
    template_name = "tag_list.html"
    context_object_name = "tags"


class TagDetailView(DetailView):
    model = Tag
    template_name = "tag_detail.html"
    context_object_name = "tag"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["analyses"] = self.object.analysis_genres.all()
        context["films"] = self.object.films.all()
        context["teaching_resources"] = self.object.tr_tags.all()
        return context


class BibliographyListView(ListView):
    model = BibliographyItem
    template_name = "bibliography.html"


class BucketItemsView(View):
    @method_decorator(login_required)
    def get(self, request):
        not_ckeditor_browser = request.GET.get("not_ckeditor_browser")
        ckeditor_func_num = request.GET.get("CKEditorFuncNum")

        session = boto3.Session(
            aws_access_key_id=AWS_ACCESS_KEY_ID,
            aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        )

        s3 = session.resource("s3")
        bucket = s3.Bucket(AWS_STORAGE_BUCKET_NAME)
        bucket_url = f"https://{bucket.name}.s3.eu-west-2.amazonaws.com/"

        response = bucket.objects.filter(Prefix="media/")
        items = [obj.key for obj in response]
        item_data = {"items": {}}
        for item in items:
            item_url = bucket_url + item
            match = re.search(r"media/(files|editor)/(.+)", item)
            if match:
                item_name = match.group(2)

            item_data["items"][item] = {"url": item_url, "name": item_name}

        context = {
            "item_data": item_data,
            "not_ckeditor_browser": not_ckeditor_browser,
            "ckeditor_func_num": ckeditor_func_num,
        }

        return render(request, "bucket_items.html", context)


def custom_404(request, exception=None):
    return render(request, "404.html", {}, status=404)


def downloadAnalysis(request, pk):
    analysis = Analysis.objects.get(pk=pk)
    template_name = "downloads/analysis.html"

    # Render the template with the context data
    html = render_to_string(template_name, {"analysis": analysis})

    # Remove images when creating the PDF
    soup = BeautifulSoup(html, "html.parser")
    for image in soup.find_all("img"):
        image.decompose()

    # Create an HTTP response with the PDF file
    response = HttpResponse(content_type="application/pdf")

    response[
        "Content-Disposition"
    ] = f"attachment; filename*=UTF-8''{quote(analysis.title)}.pdf;filename={analysis.title}.pdf"

    status = pisa.CreatePDF(str(soup), dest=response)

    if not status.err:
        return response

mod_app/templates/analysis_detail.html
{% extends "base.html" %} {% load i18n %} {% block title %}{{ analysis.title }} (Analysis) {% endblock %} {% block content %}
  <div class="teaching-analysis-detail-container">
    <a href="{% url 'analysis_list' %}" class="back-to">&larr; Back to all analyses</a>
    <div class="columnar-area">
      <div>
        <button class="btn teaching-analysis__download" onclick="downloadAnalysis(event,{{analysis.pk}})" type="button">
          <p>Download PDF</p>
          <div class="loader hidden"></div>
        </button>
      </div>

      <div id="analysis__info" class="info">
        <div id="topics">
          <h4>Topics</h4>
          {% for topic in analysis.topics.all %}
            <span class="tag">{{topic.name}}</span>
          {%empty%}
            <p>N/A</p>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="teaching-analysis__content-wrapper">
      <div class="heading"><h1 id="title">{{analysis.title}}</h1></div>
      {% include "partial/teaching_analysis_tab_area.html" with model=analysis modelname="analysis" %}
    </div>
  </div>
  <script src="{% static 'js/downloadAnalysis.js' %}"></script>
{% endblock %}

mod_app/templates/base.html
{% extends "foundation.html" %} {% load i18n %} {% block body %}
  <body>
  {% comment %} header area {% endcomment %}

    <div class="title-bar">
      <div class="title-bar__icons">
        {% if user.is_authenticated and user.is_staff %}
          <a href="/admin">
            <span title="Admin dashboard" class="material-symbols-outlined"> dashboard </span>
          </a>

        {% else %}
          <a href="{% url 'admin:index' %}">
            <span title="Log in" class="material-symbols-outlined"> login </span>
          </a>
        {% endif %} {% if user.is_authenticated%}
          <span class="material-symbols-outlined" id="menu-icon"> menu </span>

          <div class="drawer" id="drawer">
        <!-- Content of drawer goes here -->
            <div class="drawer__content">
              <div class="drawer__menu-icons">
            {% comment %}
            <div class="toggle-container">
              <span class="toggle-label">Toggle Dark Mode:</span>
              <label class="switch">
                <input type="checkbox" id="toggle" />
              </label>
            </div>
            {% endcomment %}
                <span title="dark mode: on" class="material-symbols-outlined sm darkmode"> dark_mode </span>
                {% if user.is_authenticated %} {% if user.is_staff %}
                  <a href="/admin">
                    <span title="Admin dashboard" class="material-symbols-outlined sm"> dashboard </span>
                  </a>
                {% endif %}
                  <a href="{% url 'logout' %}">
                    <span title="Log out" class="material-symbols-outlined sm"> logout </span>
                  </a>

                {% endif %}
              </div>
              <button id="drawer__button--close" aria-label="Close Menu">&times;</button>
              <h2 class="drawer__heading">Explore</h2>
              <ul class="drawer__list-nav">
                <li>
                  <a href="{% url 'film_list' %}?page=1"><span class="material-symbols-outlined">theaters</span> Films</a>
                </li>
                <li>
                  <a href="{% url 'analysis_list' %}">
                    <span class="material-symbols-outlined">description</span>
                    Analyses: Critical Essays and Discussions</a
                    >
                  </li>
                  <li>
                    <a href="{% url 'bibliography' %}"
                    ><span class="material-symbols-outlined">menu_book</span>
                      Bibliography
                    </a>
                  </li>
            {% comment %}
            <li>
              <a href="{% url 'tr_list' %}"
                ><span class="material-symbols-outlined">topic</span>
                Teaching Resources Available
              </a>
            </li>
            <li>
              <a href="{% url 'location_list' %}"
                ><span class="material-symbols-outlined">map</span>
                Locations
              </a>
            </li>
            {% endcomment %}
                  <li>
                    <a href="{% url 'tag_list' %}"
                    ><span class="material-symbols-outlined">label</span>
                      Tags
                    </a>
                  </li>
            {% comment %}
            <li>
              <a href="{% url 'search' %}"
                ><span class="material-symbols-outlined">search</span>
                Search
              </a>
            </li>
            {% endcomment %}
                </ul>
              </div>
            </div>
        {% endif %}
      </div>
      <a href="{% url 'home' %}" class="link--home">
        <div class="title-logo">
          <img id="title__logo-img" src="{% static 'images/logos/mod_lady_grey.png' %}" alt="MOD logo" />
        </div>
        <h2 class="title--mobile">MUSEUM of DREAMWORLDS</h2>
      </a>

      {% block non_production_message %} {% if not request.get_host|lower == 'museumofdreamworlds.org' %}
        <span style="color: orange; padding: 10px; position: absolute; left: 2vw; top: 10px"> STAGING </span>
      {% endif %} {% endblock %} {% include "components/logo_text.html" with extra_classes="title__logo-text" %}
    </div>

    {% block notice %} {% if not user.is_authenticated %}
      <div class="title--construction">
        <h1 class="title__text--construction">
          {% trans "NOTICE: This site is currently under construction." %}
          <br />
          <small>{% trans "Read below for more information" %} </small>
        </h1>
      </div>
      <div class="project-notice">
        <p>This site is under construction and will be launched around summer 2026 as an outcome of the AHRC-funded project Museum of Dreamworlds: Silent Antiquity Films in the BFI National Archive (2023-26).</p>
        <p>The project seeks to establish a better understanding of both the modern reception of classical antiquity and the transnational history of silent cinema. It investigates how, thanks to cinema, classical antiquity was rendered a powerfully immersive democratic dreamworld while, thanks to classical antiquity, cinema laid claim to the status of an educative art - a museum of ancient dreamworlds. The project will produce a systematic analysis of the c. 60 silent film prints in the British National Film Archive (BFI) that engage with ancient Greece and Rome and, thereby, situate the UK firmly within the global network that produced, exhibited, and consumed the classical antiquity films of the early twentieth century.</p>
        <p>The project team are creating an online resource - a digital museum of those dreamworlds - that will include direct access to prints and teaching resources in order to provide an important future use for the films beyond academia and the archive - in cinemas, schools, heritage sites, and museums.</p>
        <p>The project team comprises PI Maria Wyke (UCL), PDRA Aylin Atacan (UCL), Co-I Ivo Blom (Vrije Universiteit Amsterdam), and Co-I Bryony Dixon (BFI). Further information on the project and its activities can be found, for now, at:<a href="https://www.ucl.ac.uk/classics/research/research-projects/museum-dream-worlds"> Museum of Dreamworlds at UCL</a></p>
        <p>If you'd like to get in touch, send us an email at <a href="mailto:museumofdreamworlds@ucl.ac.uk">museumofdreamworlds@ucl.ac.uk</a></p>
      </div>
    {% endif %} {% endblock %} {% block heading %} {% endblock %}
  <!--[if lt IE 7]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p> <!
  [endif]-->{% block trailer %}{% endblock %}
    <main>{% if user.is_authenticated %} {% block content %} {% endblock %} {% endif %}</main>
  {% comment %} javascript imports {% endcomment %}
    <script src="" async defer></script>
    <script type="module" src="{% static 'js/main.js' %}"></script>
  </body>
{% comment %} footer area {% endcomment %}
  <footer class="footer">
    <a href="{% url 'home' %}">
      <div class="footer-logo">
        <img id="footer__logo-img" src="{% static 'images/logos/mod_footer_logo.png' %}" alt="MOD logo" />
        {% include "components/logo_text.html" with extra_classes="footer__logo-text" %}
      </div>
    </a>
    <div class="footer__collab-logos-area">{% include "components/collab_logos.html" %}</div>
    <div class="footer__nav">
      <ul class="footer__nav--top-row">
        <h5>Explore</h5>
        <li><a href="{% url 'film_list' %}">Films</a></li>
      {% comment %}
      <li><a href="#">Search</a></li>
      {% endcomment %}
        <li><a href="{% url 'analysis_list' %}">Analyses</a></li>
      {% comment %}
      <li><a href="{% url 'tr_list' %}">Teaching Resources</a></li>
      {% endcomment %} {% comment %}
      <li><a href="#">Locations</a></li>
      {% endcomment %}
        <li><a href="#">Tags</a></li>
      </ul>
      <ul class="footer__nav--bottom-row">
        <h5>About</h5>
      {% comment %}
      <li><a href="#">About us</a></li>
      {% endcomment %} {% comment %}
      <li><a href="#">Blog </a></li>
      {% endcomment %} {% comment %}
      <li><a href="#">Collaborators</a></li>
      {% endcomment %}
        <li><a href="mailto:museumofdreamworlds@ucl.ac.uk">Contact</a></li>
      </ul>
    </div>
    <div class="footer__collab-logos-area--mobile">{% include "components/collab_logos.html" %}</div>
  </footer>
{% endblock %}

mod_app/templates/bibliography.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Bibliography' %} {% endblock %}
{% block content %}
    <div class="page__description">
        <h3>Bibliography for all items on this website</h3>
    </div>
    <div class="bibliography__area">
        {% for bib in bibliographyitem_list %}
            <div class="bibliography__item {% cycle 'ro' 're' %}">
                <div>{{bib.full_citation|safe}}</div>
                <ul class="no-list-style bib__ref-list">
                    <li><strong>Films:</strong> {% for film in bib.films.all %}<a href="{% url 'film_detail' pk=film.pk %}">{{film.title}}</a> {% endfor %}</li>
                    <li><strong>Analyses:</strong> {% for analysis in bib.analyses.all %}<a href="{% url 'analysis_detail' pk=analysis.pk %}">{{analysis.title}}</a> {% endfor %}</li>
                    <li><strong>Teaching Resources:</strong> {% for tr in bib.teaching_resources.all %}<a href="{% url 'tr_detail' pk=tr.pk %}">{{tr.title}}</a> {% endfor %}</li>
                </ul>
            </div>

        {% endfor %}
{% endblock %}

mod_app/templates/email_template_delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Museum of Dreamworlds Mail</title>
    </head>
    <body>
        <div>
            <p>Hello all,</p>

            <p>{{updated_by}} has deleted {{ instance }} from the {{website}} website</p>

            <p>Happy Researching!</p>
            <small><em> Please note this is an automated message</em></small>
        </div>
    </body>
</html>

mod_app/templates/email_template_new.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Museum of Dreamworlds Mail</title>
    </head>
    <body>
        <div>
            <p>Hello all,</p>

            <p>{{updated_by}} has added <a href='{{instance_url}}'>{{ instance }}</a> to the {{website}} website </p>
            <p>Click <a href='{{instance_admin_url}}'>here</a> to see the changes in the admin interface. </p>


            <p>Happy Researching!</p>
            <small><em> Please note this is an automated message</em></small>
        </div>
    </body>
</html>

mod_app/templates/email_template_update.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Museum of Dreamworlds Mail</title>
    </head>
    <body>
        <div>
            <p>Hello all,</p>

            <p>{{updated_by}} has made changes to <a href='{{instance_url}}'>{{ instance }}</a> on the {{website}} website</p>
            <p>Click <a href='{{instance_admin_url}}'>here</a> to see the changes in the admin interface.</p>


            <p>Happy Researching!</p>
            <small><em> Please note this is an automated message</em></small>
        </div>
    </body>
</html>

mod_app/templates/film_list.html
{% extends "base.html" %} {% load i18n %} {% block title %}{% trans 'Films' %} {% endblock %} {% block content %} {% with page_obj=page_obj is_paginated=is_paginated page=page %} {% include "components/list_page_description.html" with model="film" view="film_list" %} {% endwith %} {% include "partial/film_card_grid.html"%} {% if is_paginated %} {% include "components/pagination_buttons.html" %} {% endif %} {% endblock %}

mod_app/templates/tr_list.html
{% extends "base.html" %} {% load i18n %} {% block title %}{% trans 'Teaching Resources' %} {% endblock %} {% block content %} {% with page_obj=page_obj is_paginated=is_paginated page=page %}{% include "components/list_page_description.html" with model="tr" description=" Teaching Resources available on this site" view="tr_list" %}{% endwith %}
  <div class="card-grid">
    {% for tr in teachingresources_list %}
      <a href="{% url 'tr_detail' pk=tr.pk %}"> {% include "components/card.html" with obj=tr %} </a>
    {% endfor %}
  </div>

  {% if is_paginated %} {% include "components/pagination_buttons.html" %} {% endif %} {% endblock %}